name: ZMK Build + Keymap Render

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: zmk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ZMK firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      # Optional: name of the zip artifact the reusable workflow uploads
      archive_name: firmware
    secrets: inherit

  keymap_render:
    name: Keymap SVG (sofle)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install keymap-drawer (pinned deps)
        run: |
          python -m pip install --upgrade pip
          pip install "keymap-drawer==0.21.0" "tree-sitter==0.20.4" "tree-sitter-devicetree==0.20.1"

      - name: Render sofle.keymap to SVG
        continue-on-error: true
        run: |
          set -euxo pipefail
          mkdir -p out
          # Parse the ZMK keymap and draw an SVG
          python -m keymap_drawer parse -z config/sofle.keymap -o out/sofle.yaml
          python -m keymap_drawer draw  -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: |
            out/keymap-sofle.svg
            out/sofle.yaml
          if-no-files-found: warn
