name: ZMK Build + Keymap Render

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ---------- Firmware builds via reusable ZMK workflow ----------
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  # ---------- Keymap SVG render (runs once) ----------
  keymap_svg:
    name: Keymap SVG (sofle)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Pin versions so keymap_drawer works with the Tree-sitter API it expects
      - name: Install keymap-drawer (pin compatible versions)
        run: |
          python -m pip install --upgrade pip
          python -m pip install "keymap-drawer==0.19.0" "tree-sitter==0.20.4" "tree-sitter-devicetree==0.20.2"

      - name: Render keymap to SVG
        run: |
          set -euxo pipefail
          mkdir -p out
          # Parse your ZMK keymap (adjust path if your file name differs)
          python -m keymap_drawer parse -z config/sofle.keymap -o out/sofle.yaml
          python -m keymap_drawer draw -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
          if-no-files-found: error

