name: ZMK Build + Keymap

on: [push, pull_request, workflow_dispatch]

jobs:
  # Official ZMK reusable workflow – reads your root-level build.yaml
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  # Extra: render a keymap image from your config (optional, but handy)
  keymap:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # <-- pin to a supported version

      - name: Install keymap-drawer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "keymap-drawer>=0.15,<1"
          keymap-drawer --version

      - name: Render keymap to SVG
        run: |
          mkdir -p out
          keymap-drawer parse -z config -o out/sofle.yaml
          keymap-drawer draw -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
