name: ZMK Build + Keymap

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-left:
    name: Build (nice_nano_v2, sofle_left)
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      board: nice_nano_v2
      shield: sofle_left

  build-right:
    name: Build (nice_nano_v2, sofle_right)
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      board: nice_nano_v2
      shield: sofle_right

  render-keymap:
    name: Render keymap SVG
    runs-on: ubuntu-latest
    needs: [build-left, build-right]  # optional; remove if you want it to run independently
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install keymap-drawer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "keymap-drawer>=0.15,<1.0"

      - name: Render to SVG
        run: |
          set -euxo pipefail
          mkdir -p out
          python3 -m keymap_drawer.cli parse -z config/sofle.keymap -o out/sofle.yaml
          python3 -m keymap_drawer.cli draw -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
          if-no-files-found: warn

