name: ZMK Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ---------- Firmware builds via reusable ZMK workflow ----------
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

