name: ZMK Build + Keymap

on: [push, pull_request, workflow_dispatch]

jobs:
  # Official ZMK reusable workflow – reads your root-level build.yaml
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  # Extra: render a keymap image from your config (optional, but handy)
  keymap:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # OPTIONAL: only needed if you want to call `keymap-drawer` directly
      - name: Add Python bin to PATH
        run: echo "$pythonLocation/bin" >> $GITHUB_PATH

      - name: Install keymap-drawer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "keymap-drawer>=0.20,<1"

      # If you added the PATH step above, you can use the CLI:
      # - name: Render keymap to SVG
      #   run: |
      #     mkdir -p out
      #     keymap-drawer parse -z config -o out/sofle.yaml
      #     keymap-drawer draw -c out/sofle.yaml -o out/keymap-sofle.svg

      # Otherwise, keep using the module form (no PATH tweak needed):
      - name: Render keymap to SVG
        run: |
          mkdir -p out
          python -m keymap_drawer parse -z config -o out/sofle.yaml
          python -m keymap_drawer draw -c out/sofle.yaml -o out/keymap-sofle.svg