name: ZMK Build + Keymap

on: [push, pull_request, workflow_dispatch]

jobs:
  # Official ZMK reusable workflow – reads your root-level build.yaml
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  # Extra: render a keymap image from your config (optional, but handy)
  keymap:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install keymap-drawer
        run: python -m pip install --upgrade pip && pip install keymap-drawer
      - name: Render keymap to SVG
        run: |
          mkdir -p out
          python -m keymap_drawer.cli parse -z config -o out/sofle.yaml
          python -m keymap_drawer.cli draw -c out/sofle.yaml -o out/keymap-sofle.svg
      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
