name: ZMK Build + Diagnostics

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # --- Firmware build (re-uses ZMK's workflow and your root-level build.yaml) ---
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    secrets: inherit
    with:
      archive_name: firmware
      # artifact-retention-days: 7  # optional

  # --- Keymap render (separate job so we control Python/pip) ---
  keymap:
    name: Render keymap SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print Python info
        run: |
          which python
          python -V

      - name: Install keymap-drawer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "keymap-drawer>=0.15,<1.0"
          python - <<'PY'
          import sys, pkgutil
          print("PYTHON:", sys.executable)
          print("HAS keymap_drawer?", bool(pkgutil.find_loader("keymap_drawer")))
          import keymap_drawer, keymap_drawer.cli
          print("keymap_drawer version:", getattr(keymap_drawer, "__version__", "unknown"))
          PY

      - name: Render keymap to SVG
        run: |
          mkdir -p out
          # Point directly at your .keymap file (not the folder)
          python -m keymap_drawer.cli parse -z config/sofle.keymap -o out/sofle.yaml
          python -m keymap_drawer.cli draw -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
