name: ZMK Build + Diagnostics

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Uses ZMK’s official reusable workflow. It reads build targets from build.yaml in your repo root.
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  render-keymap:
    # Independent job that renders your keymap SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install keymap-drawer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "keymap-drawer>=0.15,<1.0"

      - name: Render keymap to SVG
        run: |
          mkdir -p out
          # IMPORTANT: point to the actual .keymap file (not the folder)
          python -m keymap_drawer.cli parse -z config/sofle.keymap -o out/sofle.yaml
          python -m keymap_drawer.cli draw -c out/sofle.yaml -o out/keymap-sofle.svg

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
          if-no-files-found: error
