name: ZMK Build + Keymap Render

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # --- Firmware build via ZMK's reusable workflow ---
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      # Path to your ZMK config folder in this repo
      config_path: config
      # The reusable workflow will load the build matrix from the repo-root build.yaml

  # --- Render a keymap SVG (runs once, after build) ---
  keymap_svg:
    name: Keymap SVG (sofle)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install keymap-drawer (pinned) + sanity check
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          # Known-good set to avoid tree-sitter API mismatch
          python -m pip install \
            "keymap-drawer==0.19.0" \
            "tree-sitter==0.20.4" \
            "tree-sitter-devicetree==0.20.2"
          python - <<'PY'
          import sys
          from tree_sitter import Query
          print("Python:", sys.version)
          print("Query.captures present?", hasattr(Query, "captures"))
          PY

      - name: Render keymap to SVG
        run: |
          set -euxo pipefail
          mkdir -p out
          if [ -f "config/sofle.keymap" ]; then
            python -m keymap_drawer parse -z config/sofle.keymap -o out/sofle.yaml
            python -m keymap_drawer draw  -c out/sofle.yaml  -o out/keymap-sofle.svg
            ls -lah out
          else
            echo "Keymap file not found at config/sofle.keymap"
            exit 1
          fi

      - name: Upload keymap image
        uses: actions/upload-artifact@v4
        with:
          name: keymap-image
          path: out/keymap-sofle.svg
          if-no-files-found: error

